// Generated by Apple Swift version 2.1 (swiftlang-700.1.101.6 clang-700.1.76)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if defined(__has_include) && __has_include(<uchar.h>)
# include <uchar.h>
#elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
#endif

typedef struct _NSZone NSZone;

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted) 
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
#endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
#if defined(__has_feature) && __has_feature(modules)
@import ObjectiveC;
@import Foundation;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@class TypedID;
@class NSCoder;


/// Represents Target
SWIFT_CLASS("_TtC10ThingIFSDK13AbstractThing")
@interface AbstractThing : NSObject <NSCoding>
@property (nonatomic, readonly, strong) TypedID * __nonnull typedID;
@property (nonatomic, readonly, copy) NSString * __nullable accessToken;
@property (nonatomic, readonly, copy) NSString * __nonnull thingID;
@property (nonatomic, readonly, copy) NSString * __nonnull vendorThingID;
- (void)encodeWithCoder:(NSCoder * __nonnull)aCoder;
- (nonnull instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;

/// Init
///
/// \param thingID ID of thing
///
/// \param vendorThingID ID of vendor thing
///
/// \param accessToken Access token of the target, can nil.
- (nonnull instancetype)initWithThingID:(NSString * __nonnull)thingID vendorThingID:(NSString * __nonnull)vendorThingID accessToken:(NSString * __nullable)accessToken OBJC_DESIGNATED_INITIALIZER;
- (BOOL)isEqual:(id __nullable)object;
@end

@class NSDictionary;


/// Class represents And clause.
SWIFT_CLASS("_TtC10ThingIFSDK9AndClause")
@interface AndClause : NSObject <NSCoding>
- (nonnull instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * __nonnull)aCoder;

/// Get Clause as NSDictionary instance
///
/// \returns  a NSDictionary instance.
- (NSDictionary * __nonnull)toNSDictionary;
@end



/// Represents Kii Cloud Application
SWIFT_CLASS("_TtC10ThingIFSDK3App")
@interface App : NSObject <NSCoding>

/// ID of the App
@property (nonatomic, readonly, copy) NSString * __nonnull appID;

/// Key of the APP
@property (nonatomic, readonly, copy) NSString * __nonnull appKey;

/// Host name to which the app connects
@property (nonatomic, readonly, copy) NSString * __nonnull hostName;

/// Base URL of the apis used by the app
@property (nonatomic, readonly, copy) NSString * __nonnull baseURL;

/// Name of the site to which the app belongs
@property (nonatomic, readonly, copy) NSString * __nonnull siteName;

/// Conforms to NSCoding
- (nonnull instancetype)initWithCoder:(NSCoder * __nonnull)decoder;

/// Conforms to NSCoding
- (void)encodeWithCoder:(NSCoder * __nonnull)coder;
@end



/// App Builder provides fine grained controll over createing App instance. Private/ Dedicated Kii Cloud users will use it. Public Kii Cloud user who uses apps created on https://developer.kii.com does not need to interact with this Builder. Just use App(appID:appKey:site) constructor is fine.
SWIFT_CLASS("_TtC10ThingIFSDK10AppBuilder")
@interface AppBuilder : NSObject

/// Init the Builder.
///
/// <code>- Parameter appID: ID of the app.
/// - Parameter appKey: Key of the app.
/// - Parameter hostName: Host name to which the app connects
/// 
/// </code>
- (nonnull instancetype)initWithAppID:(NSString * __nonnull)appID appKey:(NSString * __nonnull)appKey hostName:(NSString * __nonnull)hostName OBJC_DESIGNATED_INITIALIZER;

/// Set port number. This method call is optional. By default no port number is used to connect to the cloud.
///
/// <code>- Parameter port: port number. 0 or less than 0 would be ignored.
/// - Returns: AppBuilder instance.
/// 
/// </code>
- (AppBuilder * __nonnull)setPort:(int32_t)port;

/// Set the API endpoint URL schema This method call is optional. By default "https" is used. You can override the URL schema with this method.
///
/// <code>- Parameter urlSchema: API endpoit URL schema
/// - Returns: AppBuilder instance.
/// 
/// </code>
- (AppBuilder * __nonnull)setUrlSchema:(NSString * __nonnull)urlSchema;

/// Set site name. This method call is optional. By default site name is set to "CUSTOM". This site name should match with your Gateway Agent configuration if you interact Gateway Agent with this SDK.
///
/// <code>- Parameter siteName: site name.
/// - Returns: AppBuilder instance.
/// 
/// </code>
- (AppBuilder * __nonnull)setSiteName:(NSString * __nonnull)siteName;

/// Build App instance
///
/// <code>- Returns: App instance
/// 
/// </code>
- (App * __nonnull)build;
@end

@class NSDate;


/// Class represents Command
SWIFT_CLASS("_TtC10ThingIFSDK7Command")
@interface Command : NSObject <NSCoding>
- (void)encodeWithCoder:(NSCoder * __nonnull)aCoder;
- (nonnull instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;

/// ID of the Command.
@property (nonatomic, readonly, copy) NSString * __nonnull commandID;

/// ID of the Command Target.
@property (nonatomic, readonly, strong) TypedID * __nonnull targetID;

/// ID of the issuer of the Command.
@property (nonatomic, readonly, strong) TypedID * __nonnull issuerID;

/// Name of the Schema of which this Command is defined.
@property (nonatomic, readonly, copy) NSString * __nonnull schemaName;

/// Version of the Schema of which this Command is defined.
@property (nonatomic, readonly) NSInteger schemaVersion;

/// Actions to be executed.
@property (nonatomic, readonly, copy) NSArray<NSDictionary<NSString *, id> *> * __nonnull actions;

/// Results of the action.
@property (nonatomic, readonly, copy) NSArray<NSDictionary<NSString *, id> *> * __nonnull actionResults;

/// ID of the trigger which fired this command
@property (nonatomic, copy) NSString * __nullable firedByTriggerID;

/// Creation time of the Command.
@property (nonatomic, strong) NSDate * __nullable created;

/// Modification time of the Command.
@property (nonatomic, strong) NSDate * __nullable modified;

/// Title of the Command
@property (nonatomic, copy) NSString * __nullable title;

/// Description of the Command
@property (nonatomic, copy) NSString * __nullable commandDescription;

/// Metadata of the Command
@property (nonatomic, copy) NSDictionary<NSString *, id> * __nullable metadata;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (BOOL)isEqual:(id __nullable)object;
@end



/// Form of a command.
///
/// This class contains data in order to create <code>Command
/// </code> with
/// <code>ThingIFAPI.postNewCommand(_:completionHandler:)
/// </code>.
///
/// Mandatory data are followings:
///
/// <ul><li>Schema name</li><li>Schema version</li><li>List of actions</li></ul>
/// Optional data are followings:
///
/// <ul><li>Title of a schema</li><li>Description of a schema</li><li>Meta data of a schema</li></ul>
SWIFT_CLASS("_TtC10ThingIFSDK11CommandForm")
@interface CommandForm : NSObject <NSCoding>

/// Schema name.
@property (nonatomic, readonly, copy) NSString * __nonnull schemaName;

/// Schema version.
@property (nonatomic, readonly) NSInteger schemaVersion;

/// List of actions.
@property (nonatomic, readonly, copy) NSArray<NSDictionary<NSString *, id> *> * __nonnull actions;

/// Title of a command.
@property (nonatomic, readonly, copy) NSString * __nullable title;

/// Description of a command.
@property (nonatomic, readonly, copy) NSString * __nullable commandDescription;

/// Meta data of ad command.
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * __nullable metadata;

/// Initializer of CommandForm instance.
///
/// \param schemaName Schema name.
///
/// \param schemaVersion Schema version.
///
/// \param actions List of actions. Must not be empty.
///
/// \param title Title of a command. This should be equal or
/// less than 50 characters.
///
/// \param description Description of a comand. This should be
/// equal or less than 200 characters.
///
/// \param metadata Meta data of a command.
- (nonnull instancetype)initWithSchemaName:(NSString * __nonnull)schemaName schemaVersion:(NSInteger)schemaVersion actions:(NSArray<NSDictionary<NSString *, id> *> * __nonnull)actions title:(NSString * __nullable)title commandDescription:(NSString * __nullable)commandDescription metadata:(NSDictionary<NSString *, id> * __nullable)metadata OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * __nonnull)aCoder;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end



/// Class represents Condition
SWIFT_CLASS("_TtC10ThingIFSDK9Condition")
@interface Condition : NSObject <NSCoding>
- (nonnull instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * __nonnull)aCoder;

/// Get Condition as NSDictionary instance
///
/// <code>- Returns: a NSDictionary instance
/// 
/// </code>
- (NSDictionary * __nonnull)toNSDictionary;
@end


SWIFT_CLASS("_TtC10ThingIFSDK7EndNode")
@interface EndNode : AbstractThing
- (nonnull instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithThingID:(NSString * __nonnull)thingID vendorThingID:(NSString * __nonnull)vendorThingID accessToken:(NSString * __nullable)accessToken OBJC_DESIGNATED_INITIALIZER;
@end



/// Class represents Equals clause.
SWIFT_CLASS("_TtC10ThingIFSDK12EqualsClause")
@interface EqualsClause : NSObject <NSCoding>

/// Initialize with String left hand side value.
///
/// \param field Name of the field to be compared.
///
/// \param string Left hand side value to be compared.
- (nonnull instancetype)initWithField:(NSString * __nonnull)field stringValue:(NSString * __nonnull)stringValue;

/// Initialize with Int left hand side value.
///
/// \param field Name of the field to be compared.
///
/// \param integer Left hand side value to be compared.
- (nonnull instancetype)initWithField:(NSString * __nonnull)field intValue:(NSInteger)intValue;

/// Initialize with Bool left hand side value.
///
/// \param field Name of the field to be compared.
///
/// \param bool Left hand side value to be compared.
- (nonnull instancetype)initWithField:(NSString * __nonnull)field boolValue:(BOOL)boolValue;
- (nonnull instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder;
- (void)encodeWithCoder:(NSCoder * __nonnull)aCoder;

/// Get Clause as NSDictionary instance
///
/// \returns  a NSDictionary instance.
- (NSDictionary * __nonnull)toNSDictionary;
@end


SWIFT_CLASS("_TtC10ThingIFSDK7Gateway")
@interface Gateway : AbstractThing
- (nonnull instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithThingID:(NSString * __nonnull)thingID vendorThingID:(NSString * __nonnull)vendorThingID accessToken:(NSString * __nullable)accessToken OBJC_DESIGNATED_INITIALIZER;
@end

@class NSURL;

SWIFT_CLASS("_TtC10ThingIFSDK10GatewayAPI")
@interface GatewayAPI : NSObject <NSCoding>
@property (nonatomic, readonly, copy) NSString * __nullable tag;
@property (nonatomic, readonly, strong) App * __nonnull app;
@property (nonatomic, readonly, strong) NSURL * __nonnull gatewayAddress;
- (void)encodeWithCoder:(NSCoder * __nonnull)aCoder;
- (nonnull instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;

/// Check if user is logged in to the Gateway.
///
/// <code>- Returns: true if user is logged in, false otherwise.
/// 
/// </code>
- (BOOL)isLoggedIn;

/// Get Access Token
///
/// <code>- Returns: Access token
/// 
/// </code>
- (NSString * __nullable)getAccessToken;

/// Clear all saved instances in the NSUserDefaults.
+ (void)removeAllStoredInstances;

/// Remove saved specified instance in the NSUserDefaults.
///
/// <code>- Parameter tag: tag of the GatewayAPI instance or nil for default tag
/// 
/// </code>
+ (void)removeStoredInstances:(NSString * __nullable)tag;

/// Save this instance This method use NSUserDefaults. Should not use the key "GatewayAPI_INSTANCE", this key is reserved.
- (void)saveInstance;
@end


@interface NSData (SWIFT_EXTENSION(ThingIFSDK))
- (NSString * __nonnull)hexString;
@end


@interface NSError (SWIFT_EXTENSION(ThingIFSDK))
@end


@interface NSLock (SWIFT_EXTENSION(ThingIFSDK))
@end


@interface NSNumber (SWIFT_EXTENSION(ThingIFSDK))
- (BOOL)isBool;
- (BOOL)isDouble;
- (BOOL)isInt;
@end


@interface NSOperation (SWIFT_EXTENSION(ThingIFSDK))
@end



/// Class represents NotEquals clause.
SWIFT_CLASS("_TtC10ThingIFSDK15NotEqualsClause")
@interface NotEqualsClause : NSObject <NSCoding>
- (nonnull instancetype)initWithEqualStmt:(EqualsClause * __nonnull)equalStmt OBJC_DESIGNATED_INITIALIZER;

/// Initialize with String left hand side value.
///
/// \param field Name of the field to be compared.
///
/// \param string Left hand side value to be compared.
- (nonnull instancetype)initWithField:(NSString * __nonnull)field stringValue:(NSString * __nonnull)stringValue OBJC_DESIGNATED_INITIALIZER;

/// Initialize with Int left hand side value.
///
/// \param field Name of the field to be compared.
///
/// \param integer Left hand side value to be compared.
- (nonnull instancetype)initWithField:(NSString * __nonnull)field intValue:(NSInteger)intValue OBJC_DESIGNATED_INITIALIZER;

/// Initialize with Bool left hand side value.
///
/// \param field Name of the field to be compared.
///
/// \param bool Left hand side value to be compared.
- (nonnull instancetype)initWithField:(NSString * __nonnull)field boolValue:(BOOL)boolValue OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * __nonnull)aCoder;

/// Get Clause as NSDictionary instance
///
/// \returns  a NSDictionary instance.
- (NSDictionary * __nonnull)toNSDictionary;
@end



/// Class represents Or clause.
SWIFT_CLASS("_TtC10ThingIFSDK8OrClause")
@interface OrClause : NSObject <NSCoding>
- (nonnull instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * __nonnull)aCoder;

/// Get Clause as NSDictionary instance
///
/// \returns  a NSDictionary instance.
- (NSDictionary * __nonnull)toNSDictionary;
@end



/// Represents Owner
SWIFT_CLASS("_TtC10ThingIFSDK5Owner")
@interface Owner : NSObject <NSCoding>
- (void)encodeWithCoder:(NSCoder * __nonnull)aCoder;
- (nonnull instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;

/// ID of the owner.
@property (nonatomic, readonly, strong) TypedID * __nonnull typedID;

/// Access token of the owner.
@property (nonatomic, readonly, copy) NSString * __nonnull accessToken;

/// instantiate Owner.
///
/// \param typedID ID of the Owner.
///
/// \param accessToken Access Token of the Owner.
- (nonnull instancetype)initWithTypedID:(TypedID * __nonnull)typedID accessToken:(NSString * __nonnull)accessToken OBJC_DESIGNATED_INITIALIZER;
- (BOOL)isEqual:(id __nullable)object;
@end


SWIFT_CLASS("_TtC10ThingIFSDK14PendingEndNode")
@interface PendingEndNode : NSObject <NSCoding>
@property (nonatomic, readonly, copy) NSString * __nullable vendorThingID;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * __nullable thingProperties;
@property (nonatomic, readonly, copy) NSString * __nullable thingType;
- (void)encodeWithCoder:(NSCoder * __nonnull)aCoder;
- (nonnull instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end



/// Class represents Range clause.
SWIFT_CLASS("_TtC10ThingIFSDK11RangeClause")
@interface RangeClause : NSObject <NSCoding>

/// Initialize with Int left hand side value. this works as >(greater than) if lower included is false and as >=(greater than or equals) if lower included is true.
///
/// \param field Name of the field to be compared.
///
/// \param lowerLimitInt Int lower limit value.
///
/// \param lowerIncluded True provided to include lowerLimit
- (nonnull instancetype)initWithField:(NSString * __nonnull)field lowerLimitInt:(NSInteger)lowerLimitInt lowerIncluded:(BOOL)lowerIncluded OBJC_DESIGNATED_INITIALIZER;

/// Initialize with Double left hand side value. this works as >(greater than) if lower included is false and as >=(greater than or equals) if lower included is true.
///
/// \param field Name of the field to be compared.
///
/// \param lowerLimitDouble Double lower limit value.
///
/// \param lowerIncluded True provided to include lowerLimit
- (nonnull instancetype)initWithField:(NSString * __nonnull)field lowerLimitDouble:(double)lowerLimitDouble lowerIncluded:(BOOL)lowerIncluded OBJC_DESIGNATED_INITIALIZER;

/// Initialize with Int left hand side value. this works as <(less than) if upper included is false and as <=(less than or equals) if upper included is true.
///
/// \param field Name of the field to be compared.
///
/// \param upperLimitInt Int upper limit value.
///
/// \param upperIncluded True provided to include upperLimit
- (nonnull instancetype)initWithField:(NSString * __nonnull)field upperLimitInt:(NSInteger)upperLimitInt upperIncluded:(BOOL)upperIncluded OBJC_DESIGNATED_INITIALIZER;

/// Initialize with Double left hand side value. this works as <(less than) if upper included is false and as <=(less than or equals) if upper included is true.
///
/// \param field Name of the field to be compared.
///
/// \param upperLimitDouble Double upper limit value.
///
/// \param upperIncluded True provided to include upperLimit
- (nonnull instancetype)initWithField:(NSString * __nonnull)field upperLimitDouble:(double)upperLimitDouble upperIncluded:(BOOL)upperIncluded OBJC_DESIGNATED_INITIALIZER;

/// Initialize with Range. this works in the following cases:
///
/// <ul><li>">(greater than) and <(less than)" if lower included is false and upper included is false.</li><li>">=(greater than or equals) and <(less than)" if lower included is true and upper included is false.</li><li>">(greater than) and <=(less than and equals)" if lower included is false and upper included is true.</li><li>">=(greater than and equals) and <=(less than and equals)" if lower included is true and upper included is true.</li></ul>
/// \param field Name of the field to be compared.
///
/// \param lowerLimitInt Int lower limit value.
///
/// \param lowerIncluded True provided to include lowerLimit
///
/// \param upperLimit Int upper limit value.
///
/// \param upperIncluded True provided to include upperLimit
- (nonnull instancetype)initWithField:(NSString * __nonnull)field lowerLimitInt:(NSInteger)lowerLimitInt lowerIncluded:(BOOL)lowerIncluded upperLimit:(NSInteger)upperLimit upperIncluded:(BOOL)upperIncluded OBJC_DESIGNATED_INITIALIZER;

/// Initialize with Range. this works in the following cases:
///
/// <ul><li>">(greater than) and <(less than)" if lower included is false and upper included is false.</li><li>">=(greater than or equals) and <(less than)" if lower included is true and upper included is false.</li><li>">(greater than) and <=(less than and equals)" if lower included is false and upper included is true.</li><li>">=(greater than and equals) and <=(less than and equals)" if lower included is true and upper included is true.</li></ul>
/// \param field Name of the field to be compared.
///
/// \param lowerLimitDouble Double lower limit value.
///
/// \param lowerIncluded True provided to include lowerLimit
///
/// \param upperLimit Double upper limit value.
///
/// \param upperIncluded True provided to include upperLimit
- (nonnull instancetype)initWithField:(NSString * __nonnull)field lowerLimitDouble:(double)lowerLimitDouble lowerIncluded:(BOOL)lowerIncluded upperLimit:(double)upperLimit upperIncluded:(BOOL)upperIncluded OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * __nonnull)aCoder;

/// Get Clause as NSDictionary instance
///
/// \returns  a NSDictionary instance.
- (NSDictionary * __nonnull)toNSDictionary;
@end



/// Accessor of the Thing-IF SDK version.
SWIFT_CLASS("_TtC10ThingIFSDK10SDKVersion")
@interface SDKVersion : NSObject
+ (SDKVersion * __nonnull)sharedInstance;

/// Version of the Thing-IF SDK
@property (nonatomic, copy) NSString * __nullable versionString;
@end



/// Class represents ScheduleOncePredicate.
SWIFT_CLASS("_TtC10ThingIFSDK21ScheduleOncePredicate")
@interface ScheduleOncePredicate : NSObject <NSCoding>

/// Specified schedule.
@property (nonatomic, readonly, strong) NSDate * __nonnull scheduleAt;

/// Instantiate new ScheduleOncePredicate.
///
/// <code>-Parameter scheduleAt: Specify execution schedule. It must be future date.
/// 
/// </code>
- (nonnull instancetype)initWithScheduleAt:(NSDate * __nonnull)scheduleAt OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * __nonnull)aCoder;

/// Get Json object of ScheduleOncePredicate instance
///
/// <code>- Returns: Json object as an instance of NSDictionary
/// 
/// </code>
- (NSDictionary * __nonnull)toNSDictionary;
@end



/// Class represents SchedulePredicate.
SWIFT_CLASS("_TtC10ThingIFSDK17SchedulePredicate")
@interface SchedulePredicate : NSObject <NSCoding>

/// Specified schedule. (cron tab format)
@property (nonatomic, readonly, copy) NSString * __nonnull schedule;

/// Instantiate new SchedulePredicate.
///
/// <code>-Parameter schedule: Specify schedule. (cron tab format)
/// 
/// </code>
- (nonnull instancetype)initWithSchedule:(NSString * __nonnull)schedule OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * __nonnull)aCoder;

/// Get Json object of SchedulePredicate instance
///
/// <code>- Returns: Json object as an instance of NSDictionary
/// 
/// </code>
- (NSDictionary * __nonnull)toNSDictionary;
@end


SWIFT_CLASS("_TtC10ThingIFSDK10ServerCode")
@interface ServerCode : NSObject <NSCoding>
- (void)encodeWithCoder:(NSCoder * __nonnull)aCoder;
- (nonnull instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;

/// Endpoint to call on servercode
@property (nonatomic, copy) NSString * __nonnull endpoint;

/// This token will be used to call the external appID endpoint
@property (nonatomic, copy) NSString * __nullable executorAccessToken;

/// If provided, servercode endpoint will be called for this appid. Otherwise same appID of trigger is used
@property (nonatomic, copy) NSString * __nullable targetAppID;

/// Parameters to pass to the servercode function
@property (nonatomic, copy) NSDictionary<NSString *, id> * __nullable parameters;

/// Init TriggeredServerCodeResult with necessary attributes
///
/// <code>- Parameter endpoint: Endpoint to call on servercode
/// - Parameter executorAccessToken: This token will be used to call the external appID endpoint
/// - Parameter targetAppID: If provided, servercode endpoint will be called for this appid. Otherwise same appID of trigger is used
/// - Parameter parameters: Parameters to pass to the servercode function
/// 
/// </code>
- (nonnull instancetype)initWithEndpoint:(NSString * __nonnull)endpoint executorAccessToken:(NSString * __nullable)executorAccessToken targetAppID:(NSString * __nullable)targetAppID parameters:(NSDictionary<NSString *, id> * __nullable)parameters OBJC_DESIGNATED_INITIALIZER;
- (BOOL)isEqual:(id __nullable)object;
@end


SWIFT_CLASS("_TtC10ThingIFSDK11ServerError")
@interface ServerError : NSObject <NSCoding>
- (void)encodeWithCoder:(NSCoder * __nonnull)aCoder;
- (nonnull instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, copy) NSString * __nullable errorMessage;
@property (nonatomic, readonly, copy) NSString * __nullable errorCode;
@property (nonatomic, readonly, copy) NSString * __nullable detailMessage;
- (BOOL)isEqual:(id __nullable)object;
@end


SWIFT_CLASS("_TtC10ThingIFSDK15StandaloneThing")
@interface StandaloneThing : AbstractThing
- (nonnull instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithThingID:(NSString * __nonnull)thingID vendorThingID:(NSString * __nonnull)vendorThingID accessToken:(NSString * __nullable)accessToken OBJC_DESIGNATED_INITIALIZER;
@end



/// Class represents StatePredicate
SWIFT_CLASS("_TtC10ThingIFSDK14StatePredicate")
@interface StatePredicate : NSObject <NSCoding>
@property (nonatomic, readonly, strong) Condition * __null_unspecified condition;
- (nonnull instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * __nonnull)aCoder;

/// Get StatePredicate as NSDictionary instance
///
/// <code>- Returns: a NSDictionary instance
/// 
/// </code>
- (NSDictionary * __nonnull)toNSDictionary;
@end



/// Class provides API of the ThingIF.
SWIFT_CLASS("_TtC10ThingIFSDK10ThingIFAPI")
@interface ThingIFAPI : NSObject <NSCoding>

/// Tag of the ThingIFAPI instance
@property (nonatomic, readonly, copy) NSString * __nullable tag;

/// URL of KiiApps Server
@property (nonatomic, readonly, copy) NSString * __null_unspecified baseURL;

/// The application ID found in your Kii developer console
@property (nonatomic, readonly, copy) NSString * __null_unspecified appID;

/// The application key found in your Kii developer console
@property (nonatomic, readonly, copy) NSString * __null_unspecified appKey;

/// Kii Cloud Application
@property (nonatomic, readonly, strong) App * __null_unspecified app;

/// owner of target
@property (nonatomic, readonly, strong) Owner * __null_unspecified owner;

/// Get installationID if the push is already installed. null will be returned if the push installation has not been done.
///
/// \returns  Installation ID used in IoT Cloud.
@property (nonatomic, readonly, copy) NSString * __nullable installationID;
- (void)encodeWithCoder:(NSCoder * __nonnull)aCoder;
- (nonnull instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;

/// Save this instance
- (void)saveInstance;

/// Clear all saved instances in the NSUserDefaults.
+ (void)removeAllStoredInstances;

/// Remove saved specified instance in the NSUserDefaults.
///
/// \param tag tag of the ThingIFAPI instance or nil for default tag
+ (void)removeStoredInstances:(NSString * __nullable)tag;
- (BOOL)isEqual:(id __nullable)object;
@end


@interface ThingIFAPI (SWIFT_EXTENSION(ThingIFSDK))
@end


@interface ThingIFAPI (SWIFT_EXTENSION(ThingIFSDK))
@end


@interface ThingIFAPI (SWIFT_EXTENSION(ThingIFSDK))
@end


@interface ThingIFAPI (SWIFT_EXTENSION(ThingIFSDK))
@end


@interface ThingIFAPI (SWIFT_EXTENSION(ThingIFSDK))
@end



/// Class represents Trigger
SWIFT_CLASS("_TtC10ThingIFSDK7Trigger")
@interface Trigger : NSObject <NSCoding>
- (void)encodeWithCoder:(NSCoder * __nonnull)aCoder;
- (nonnull instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;

/// ID of the Trigger
@property (nonatomic, copy) NSString * __nonnull triggerID;

/// Flag indicate whether the Trigger is enabled
@property (nonatomic) BOOL enabled;

/// Command to be fired
@property (nonatomic, strong) Command * __nullable command;

/// ServerCode to be fired
@property (nonatomic, strong) ServerCode * __nullable serverCode;

/// Title of the Trigger
@property (nonatomic, copy) NSString * __nullable title;

/// Description of the Trigger
@property (nonatomic, copy) NSString * __nullable triggerDescription;

/// Metadata of the Trigger
@property (nonatomic, copy) NSDictionary<NSString *, id> * __nullable metadata;
- (BOOL)isEqual:(id __nullable)object;
@end



/// Class represents result of server code trigged by trigger
SWIFT_CLASS("_TtC10ThingIFSDK25TriggeredServerCodeResult")
@interface TriggeredServerCodeResult : NSObject <NSCoding>
- (void)encodeWithCoder:(NSCoder * __nonnull)aCoder;
- (nonnull instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;

/// Whether the invocation succeeded
@property (nonatomic) BOOL succeeded;

/// Returned value from server code (JsonObject, JsonArray, String, Number, Boolean or null)
@property (nonatomic, strong) id __nullable returnedValue;

/// Date of the execution
@property (nonatomic, strong) NSDate * __nonnull executedAt;

/// The endpoint used in the server code invocation
@property (nonatomic, copy) NSString * __nonnull endpoint;

/// Error object of the invocation if any
@property (nonatomic, strong) ServerError * __nullable error;

/// Init TriggeredServerCodeResult with necessary attributes
///
/// <code>- Parameter succeeded: Whether the invocation succeeded
/// - Parameter returnedValue: Returned value from server code
/// - Parameter executedAt: Date of the execution
/// - Parameter endpoint: The endpoint used in the server code invocation
/// - Parameter error: Error object of the invocation if any
/// 
/// </code>
- (nonnull instancetype)initWithSucceeded:(BOOL)succeeded returnedValue:(id __nullable)returnedValue executedAt:(NSDate * __nonnull)executedAt endpoint:(NSString * __nonnull)endpoint error:(ServerError * __nullable)error OBJC_DESIGNATED_INITIALIZER;
- (id __nullable)getReturnedValue;
- (NSString * __nullable)getReturnedValueAsString;
- (NSNumber * __nullable)getReturnedValueAsNSNumber;
- (NSDictionary<NSString *, id> * __nullable)getReturnedValueAsDictionary;
- (NSArray * __nullable)getReturnedValueAsArray;
- (BOOL)isEqual:(id __nullable)object;
@end



/// Represents entity type and its ID.
SWIFT_CLASS("_TtC10ThingIFSDK7TypedID")
@interface TypedID : NSObject <NSCoding>
- (void)encodeWithCoder:(NSCoder * __nonnull)aCoder;
- (nonnull instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;

/// Type of the ID
///
/// <code>All characters in this string are lower case.
/// 
/// </code>
@property (nonatomic, readonly, copy) NSString * __nonnull type;

/// ID of the entity.
@property (nonatomic, readonly, copy) NSString * __nonnull id;

/// Ininitialize TypedID with type and id.
///
/// \param type Type of the entity. All upper case characters in
/// given string are converted to lower case.
///
/// \param id ID of the entity.
- (nonnull instancetype)initWithType:(NSString * __nonnull)type id:(NSString * __nonnull)id OBJC_DESIGNATED_INITIALIZER;
- (BOOL)isEqual:(id __nullable)object;
@end

#pragma clang diagnostic pop
